name: "Linear ids in pr description"
description: "Add linear ids from commits into description"
author: "Turtle"

inputs:
  gh-token:
    description: "The GitHub token for authentication."
    required: true

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "activity"
  color: "green"
