name: 'Linear ticket descriptions'

on:
  pull_request:

jobs:
  ticketDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          ticket-regex: "mojo-\\d+"
          section-title: 'Linear Tickets Found'
          magic-word: 'ref'
