name: "Linear ticket descriptions"

on:
  pull_request:
    types: [opened, reopened]

jobs:
  ticketDescription:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GH_TOKEN | gh auth login --with-token
      - uses: ./
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
